{{- range $repo := .Values.repositories -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ $repo }}
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: {{ $repo }}
---
{{ end }}