# A storage class will be created for each repository
repositories:
- dunedaq.opensciencegrid.org
- cms.cern.ch

# Advanced settings
# Changing these settings is not advised unless you know what you are doing
csiPlugin:
  driverName: cvmfs.csi.cern.ch
  image: juravenator/csi-cvmfsplugin:latest
  args:
    - "--nodeid=$(NODE_ID)"
    - "--csi-address=$(CSI_ADDRESS)"
    - "--drivername=$(DRIVER_NAME)"
    - "--log.level=trace"
  pluginDirectory: /var/lib/kubelet/plugins/cvmfs.csi.cern.ch
  nodeDriverImage: k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.2.0
  livenessProbeImage: k8s.gcr.io/sig-storage/livenessprobe:v2.3.0
  attacherImage: k8s.gcr.io/sig-storage/csi-attacher:v3.2.1
  provisionerImage: k8s.gcr.io/sig-storage/csi-provisioner:v2.2.1